name: Node.js CI/CD

on:
  push:
    branches: ["main"]

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
  SUPABASE_URL: ${{secrets.SUPABASE_URL}}

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      
      - name: Prepare Env
        run: |
          echo "DATABASE_URL=${{env.DATABASE_URL}}" >> .env
          echo "SUPABASE_KEY=${{env.SUPABASE_KEY}}" >> .env
          echo "SUPABASE_URL=${{env.SUPABASE_URL}}" >> .env
      - run: npm ci
      - run: pm2 restart furrmatch
